# **using Postman alternative route client extension to test http request**  

###
GET  http://localhost:5000/data

#_____________________________________________________________________

###
POST http://localhost:5000/data
content-type: application/json

{
    "location": "Engineering",
    "lat": "106.39504930221123",
    "long": "-14.193891034893",
    "percentage_full": "100"
}
#_____________________________________________________________________

###
DELETE http://localhost:5000/data/6033374f4f08f5ef65e65599


#_____________________________________________________________________
###
PATCH http://localhost:5000/data/603337504f08f5ef65e6559a
content-type: application/json

{
    "location": "SO-SCI",
    "percentage_full": "1000"
}

#_____________________________________________________________________
