# **using Postman alternative route client extension to test http request**  

###
GET  http://localhost:5000/data

#_____________________________________________________________________

###
POST http://localhost:5000/data
content-type: application/json

{
    "location": "Scitech",
    "lat": "106.395049302910",
    "long": "-14.193891093893",
    "percentage_full": "95"
}
#_____________________________________________________________________

###
DELETE http://localhost:5000/data

#_____________________________________________________________________
###
PATCH http://localhost:5000/data/603336e14f08f5ef65e65597
content-type: application/json

{

     "percentage_full": "55"
}

#_____________________________________________________________________
